##===- lib/RangeAnalysis/Makefile ---------*- Makefile -*-===##

LEVEL=../..

LIBRARYNAME=RangeAnalysis

LOADABLE_MODULE=1

SOURCES= BaseRange.cpp Range.cpp RangePass.cpp WrappedRange.cpp StridedWrappedRange.cpp

include $(LEVEL)/Makefile.options
include $(LEVEL)/Makefile.common
