##===- lib/Transformations/vSSA/Makefile -------------*- Makefile -*-===##

LEVEL=../..

LIBRARYNAME = Transformations

LOADABLE_MODULE=1

SOURCES=vSSA.cpp 

include $(LEVEL)/Makefile.options
include $(LEVEL)/Makefile.common
