##===- lib/Makefile ----------------------------*- Makefile -*-===##

LEVEL=..

LIBRARYNAME=Fixpoint

LOADABLE_MODULE=1

SOURCES=FixpointSSI.cpp ArrayIndexManager.cpp

DIRS=RangeAnalysis Transformations

include $(LEVEL)/Makefile.options
include $(LEVEL)/Makefile.common
